"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { ConfigProvider } from "antd";
import { Provider } from "react-redux";
import { StoreRedux } from "@/Redux/Store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider store={StoreRedux}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#474AC9",
            },
          }}
        >
          <body className={inter.className}>{children}</body>
        </ConfigProvider>
      </Provider>
    </html>
  );
}
