"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { ConfigProvider } from "antd";

import Screens from "@/utils/Screens";
import { Grid } from "antd";
import Texting from "@/utils/Texting";

const inter = Inter({ subsets: ["latin"] });

let { useBreakpoint } = Grid;
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Desktop = {
  xs: 10,
  sm: 14,
  md: 16,
  lg: 20,
  xl: 26,
  xxl: 35,
};
const Mobile = {
  xs: 8,
  sm: 10,
  md: 12,
  lg: 18,
  xl: 22,
  xxl: 25,
};

export default function RootLayout({ children }) {
  const screen = useBreakpoint();

  // console.log(screen, "layy");

  return (
    <html lang="en">
      {/* <Provider store={StoreRedux}> */}
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: "#474AC9",
          },
        }}
      >
        <Screens.Provider value={screen}>
          <Texting.Provider value={screen.xs ? Mobile : Desktop}>
            <body
              style={{ maxWidth: "1680px", margin: "0px auto" }}
              className={inter.className}
            >
              {children}
            </body>
          </Texting.Provider>
        </Screens.Provider>
      </ConfigProvider>
      {/* </Provider> */}
    </html>
  );
}
